/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Xebia Brand System
        primary: {
          DEFAULT: 'var(--primary, #6C1D5F)',
          dark: 'var(--primary-dark, #4A1E47)',
          bright: 'var(--primary-bright, #84117C)',
          light: 'var(--primary-light, #F3E7F1)',
          50: '#F9F0F7',
          100: '#F3E7F1',
          200: '#E4C8DE',
          300: '#D5A9CB',
          400: '#B66AA5',
          500: '#6C1D5F',
          600: '#5B1952',
          700: '#4A1E47',
          800: '#3A0032',
          900: '#2A0025',
        },
        cta: {
          DEFAULT: 'var(--cta, #FF6200)',
          hover: 'var(--cta-hover, #E55800)',
          active: '#CC4F00',
          light: 'var(--cta-light, #FFF0E6)',
          50: '#FFF7F0',
          100: '#FFE8D4',
          200: '#FFD0A8',
          300: '#FFB597',
          400: '#FF8C42',
          500: '#FF6200',
          600: '#E55800',
          700: '#CC4F00',
        },
        emerald: {
          DEFAULT: 'var(--emerald, #01AC9F)',
          light: 'var(--emerald-light, #E5F7F5)',
          dark: '#008F84',
          50: '#E5F7F5',
          100: '#CBF0EC',
          200: '#9FE1CB',
          300: '#56DACC',
          400: '#01AC9F',
          500: '#01AC9F',
          600: '#008F84',
        },
        surface: {
          DEFAULT: 'var(--surface-card, #FFFFFF)',
          card: 'var(--surface-card, #FFFFFF)',
          page: 'var(--surface-page, #F7F8FC)',
          container: 'var(--surface-container, #EFEDED)',
          'container-low': 'var(--surface-container-low, #F5F3F3)',
          'container-high': 'var(--surface-container-high, #EAE8E7)',
          tint: 'var(--surface-tint, #DADCEA)',
          dim: 'var(--surface-dim, #DBDAD9)',
        },
        border: {
          DEFAULT: 'var(--border-color, #DEDEDE)',
          light: 'var(--border-subtle, rgba(255, 255, 255, 0.10))',
          medium: 'rgba(255, 255, 255, 0.15)',
        },
        danger: {
          DEFAULT: 'var(--danger-color, #B91C1C)',
          bg: 'var(--danger-bg, #FEF2F2)',
          light: '#FEE2E2',
        },
        warning: {
          DEFAULT: 'var(--warning-color, #B45309)',
          bg: 'var(--warning-bg, #FFFBEB)',
        },
        success: {
          DEFAULT: 'var(--emerald, #01AC9F)',
          bg: 'var(--success-bg, #E5F7F5)',
        },
        info: {
          bg: 'var(--info-bg, #F3E7F1)',
        },
        text: {
          primary: 'var(--text-primary, #1B1C1C)',
          secondary: 'var(--text-secondary, #51434C)',
          muted: 'var(--text-muted, #83727C)',
          inverse: 'var(--text-inverse, #FFFFFF)',
          'inverse-muted': 'rgba(255, 255, 255, 0.65)',
          'inverse-strong': 'rgba(255, 255, 255, 0.85)',
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'caption-xs': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'overline-xs': ['12px', { lineHeight: '1.5', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
        'body-base': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['20px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-xl': ['24px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-2xl': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '4px',
        xl: '8px',
        card: '16px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
        gutter: '24px',
        margin: '32px',
        base: '4px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 4px 12px rgba(0, 0, 0, 0.08)',
        'elevated': '0 8px 24px rgba(0, 0, 0, 0.12)',
        'cta': '0 4px 16px rgba(255, 98, 0, 0.32)',
        'chrome': '0 8px 40px rgba(0, 0, 0, 0.14), 0 2px 8px rgba(0, 0, 0, 0.08)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
    },
  },
  plugins: [],
};
